
server.port: 8080

# Database URL
spring.datasource.url=jdbc:mysql://database-1.cdwqgesqe16c.eu-north-1.rds.amazonaws.com:3306/myprodDb

# Credentials
spring.datasource.username=admin
spring.datasource.password=Manoj0158
