spring.application.name=helloapp

# Database URL
spring.datasource.url=jdbc:mysql://localhost:3306/teacher

# Credentials
spring.datasource.username=root
spring.datasource.password=manoj123

# Driver (optional, auto-detected)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect